#!/bin/bash
# setup-test-runner-security-group.sh
# Creates security group for test runner EC2 instance

set -e

PROFILE="${AWS_PROFILE:-cc-native-account}"
REGION="${AWS_REGION:-us-west-2}"

# Load .env file if it exists
if [ -f .env ]; then
  source .env
fi

# Get VPC ID (from .env or query CloudFormation)
if [ -z "$VPC_ID" ]; then
  echo "VPC_ID not found in .env, querying CloudFormation..."
  VPC_ID=$(aws cloudformation describe-stacks \
    --stack-name CCNativeStack \
    --query "Stacks[0].Outputs[?OutputKey=='VpcId'].OutputValue" \
    --output text \
    --profile $PROFILE \
    --region $REGION \
    --no-cli-pager)
fi

if [ -z "$VPC_ID" ]; then
  echo "Error: Could not determine VPC ID"
  exit 1
fi

echo "Using VPC ID: $VPC_ID"
echo "Using AWS Profile: $PROFILE"
echo "Using AWS Region: $REGION"

# Get your public IP address
MY_IP=$(curl -s https://checkip.amazonaws.com)
echo "Your IP: $MY_IP"

# Create security group (or get existing one)
echo "Creating security group..."
SG_ID=$(aws ec2 create-security-group \
  --group-name cc-native-test-runner-sg \
  --description "Security group for integration test runner - allows SSH from your IP" \
  --vpc-id $VPC_ID \
  --query "GroupId" \
  --output text \
  --profile $PROFILE \
  --region $REGION \
  --no-cli-pager 2>/dev/null || \
  aws ec2 describe-security-groups \
    --filters "Name=group-name,Values=cc-native-test-runner-sg" "Name=vpc-id,Values=$VPC_ID" \
    --query "SecurityGroups[0].GroupId" \
    --output text \
    --profile $PROFILE \
    --region $REGION \
    --no-cli-pager)

if [ -z "$SG_ID" ] || [ "$SG_ID" == "None" ]; then
  echo "Error: Could not create or find security group"
  exit 1
fi

echo "Security Group ID: $SG_ID"

# Allow SSH from your IP (idempotent - will fail silently if rule already exists)
echo "Adding SSH rule (port 22) from your IP..."
aws ec2 authorize-security-group-ingress \
  --group-id $SG_ID \
  --protocol tcp \
  --port 22 \
  --cidr $MY_IP/32 \
  --profile $PROFILE \
  --region $REGION \
  --no-cli-pager 2>/dev/null || echo "SSH rule may already exist"

# Get Neptune security group ID
echo "Finding Neptune security group..."
NEPTUNE_SG_ID=$(aws ec2 describe-security-groups \
  --filters "Name=group-name,Values=*NeptuneSecurityGroup*" "Name=vpc-id,Values=$VPC_ID" \
  --query "SecurityGroups[0].GroupId" \
  --output text \
  --profile $PROFILE \
  --region $REGION \
  --no-cli-pager)

if [ -z "$NEPTUNE_SG_ID" ] || [ "$NEPTUNE_SG_ID" == "None" ]; then
  echo "Warning: Could not find Neptune security group"
  echo "You may need to manually allow access from security group $SG_ID to Neptune on port 8182"
else
  echo "Neptune Security Group ID: $NEPTUNE_SG_ID"
  
  # Allow test runner to connect to Neptune (port 8182)
  echo "Adding rule to allow test runner to access Neptune (port 8182)..."
  aws ec2 authorize-security-group-ingress \
    --group-id $NEPTUNE_SG_ID \
    --protocol tcp \
    --port 8182 \
    --source-group $SG_ID \
    --profile $PROFILE \
    --region $REGION \
    --no-cli-pager 2>/dev/null || echo "Neptune access rule may already exist"
fi

# Store variables in .env.test-runner file
ENV_FILE=".env.test-runner"
cat > $ENV_FILE << EOF
# Test Runner Configuration
# Generated by setup-test-runner-security-group.sh on $(date)

TEST_RUNNER_SECURITY_GROUP_ID=$SG_ID
TEST_RUNNER_MY_IP=$MY_IP
EOF

if [ -n "$NEPTUNE_SG_ID" ] && [ "$NEPTUNE_SG_ID" != "None" ]; then
  echo "NEPTUNE_SECURITY_GROUP_ID=$NEPTUNE_SG_ID" >> $ENV_FILE
fi

echo ""
echo "✅ Security group setup complete!"
echo ""
echo "Security Group ID: $SG_ID"
echo "Configuration saved to: $ENV_FILE"
echo ""
echo "You can load these variables with:"
echo "  source $ENV_FILE"
echo ""
echo "Or use them directly in your EC2 launch command:"
echo "  --security-group-ids $SG_ID"
